apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-service-config
data:
  DB_NAME: "mydatabase"
  DB_USERNAME: "myuser"
  DB_HOST: "10.100.32.241"
  DB_PORT: "5432"
---
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  DB_PASSWORD: bXlfcGFzc3dvcmQ=
