apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
spec:
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: postgres:latest
        env:
        - name: POSTGRES_DB
          value: mydatabase
        - name: POSTGRES_USER
          value: myuser
        - name: POSTGRES_PASSWORD
          value: mypassword
            #env:
            # - name: POSTGRES_DB
            #valueFrom:
            #configMapKeyRef:
            #name: postgresql-service-config
            #key: DB_NAME
            #- name: POSTGRES_USER
            #valueFrom:
            #configMapKeyRef:
            #name: postgresql-service-config
            #key: DB_USERNAME
            #- name: POSTGRES_PASSWORD
            #valueFrom:
            #secretKeyRef:
            #name: mysecret
            #key: DB_PASSWORD
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgresql-storage
      volumes:
      - name: postgresql-storage
        persistentVolumeClaim:
          claimName: postgresql-pvc
